version: "3.3"

services:
  connector:
    build:
      context: .
      dockerfile: sync-Dockerfile
    image: custom-connector
    networks:
      - mongo_replica_net
    depends_on:
      - elastic

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    networks:
      - mongo_replica_net
    ports:
      - 9200:9200

networks:
  mongo_replica_net:
    external: true

#   config = { "_id" : "mongo-set", "members" : [{"_id" : 0,"host" : "mongo1:27017"},{"_id" : 1,"host" : "mongo2:27017"},{"_id" : 2,"host" : "mongo3:27017"}]}
#   rs.initiate(config)