version: "3.3"

services:
  connector:
    build:
      context: .
      dockerfile: sync-Dockerfile
    image: custom-connector
    networks:
      - mongo-cluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - elastic

  mongo1:
    image: mongo:3.4.19-jessie
    command: mongod --dbpath /data/db --replSet mongo-set
    networks:
      - mongo-cluster
    ports:
      - 30001:27017
  mongo2:
    image: mongo:3.4.19-jessie
    command: mongod --dbpath /data/db --replSet mongo-set
    networks:
      - mongo-cluster
    ports:
      - 30002:27017
  mongo3:
    image: mongo:3.4.19-jessie
    command: mongod --dbpath /data/db --replSet mongo-set
    networks:
      - mongo-cluster
    ports:
      - 30003:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    networks:
      - mongo-cluster
    ports:
      - 9200:9200

networks:
  mongo-cluster:

#   config = { "_id" : "mongo-set", "members" : [{"_id" : 0,"host" : "mongo1:27017"},{"_id" : 1,"host" : "mongo2:27017"},{"_id" : 2,"host" : "mongo3:27017"}]}
#   rs.initiate(config)