FROM node:10.15.1-jessie-slim

WORKDIR /tmp
COPY package.json /tmp/package.json
RUN npm install && mkdir -p /app/node_modules && cp -a ./node_modules /app/

WORKDIR /app
VOLUME /app/server/public
ENV DOCKER=true
ENV NODE_ENV=development
ENV PORT=3000

COPY . .

EXPOSE 3000
CMD ["/bin/bash", "./docker/startup.sh"]

